aws:
  dynamodb:
    region: ${AWS_DYNAMODB_REGION:us-east-1}
    table:
      clients: ${DYNAMODB_TABLE_CLIENTS:Clients}
      funds: ${DYNAMODB_TABLE_FUNDS:Funds}
      transactions: ${DYNAMODB_TABLE_TRANSACTIONS:Transactions}
      subscriptions: ${DYNAMODB_TABLE_SUBSCRIPTIONS:Subscriptions}
  sns:
    enabled: true
    topic-arn: ${SNS_TOPIC_ARN}

springdoc:
  swagger-ui:
    configUrl: /${API_BASE_PATH}/v3/api-docs/swagger-config
    url: /${API_BASE_PATH}/v3/api-docs

logging:
  level:
    com.btg.fondos: INFO
