spring:
  application:
    name: fondos-api
  profiles:
    active: local

server:
  port: 8080

app:
  jwt:
    secret: ${APP_JWT_SECRET}
    expiration-ms: ${APP_JWT_EXPIRATION_MS:86400000}
  client:
    initial-balance: ${APP_CLIENT_INITIAL_BALANCE:500000}
