aws:
  dynamodb:
    endpoint: http://localhost:8000
    region: us-east-1
  sns:
    enabled: false

app:
  jwt:
    secret: bXlTdXBlclNlY3JldEtleUZvckpXVEF1dGhlbnRpY2F0aW9uQlRHUGFjdHVhbDIwMjU=

logging:
  level:
    com.btg.fondos: DEBUG
    software.amazon.awssdk: WARN
